### ISSUE TITLE
Make dev, stage and prod envionments 

### ISSUE THREAD

**Issue by varungulati** [varungulati/dronegama#1]
Make dev, stage and production environment and link it to heroku. 

Host 3 links to dronegama like dev_dronegama.herokuapp.com, stage_dronegama.herokuapp.com and prod_dronegama@herokuapp.com

**Comment by sidgyl** [comment]
separate profiles created for stage and local Dev environments. The following steps were followed

1. A common base file was created that has all the common 
2. Two separate files for the STAGE and DEV environments were created. These files will contain environment specific properties. We have separate DB details in our case
3. Set the environment variable DJANGO_SETTINGS_MODULE to point to the environment specific properties file. 

We can create the environment file for PROD when we are ready to deploy to production
